-- Vai definir a estrutura dos dados

CREATE table usuario
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid UUID,
    nome VARCHAR(255),
    email VARCHAR(255),,
    dob date,
    CONSTRAINT pk_usuario PRIMARY KEY  (id)
);

CREATE table postagem
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid UUID,
    titulo VARCHAR(255),
    corpo VARCHAR(255),
    data_criacao TIMESTAMP WITHOUT TIME ZONE,
    usuario_id BIGINT,
    CONSTRAINT pk_postagem PRIMARY KEY (id)
);

ALTER TABLE postagem
    ADD CONSTRAINT FK_POSTAGEM_ON_USUARIO FOREIGN KEY (usuario_id) REFERENCES usuario (id)